date:
  media:
    max-width: 640
    max-height: 320
  data:
    url: /data
spring:
  application:
    name: search-service
server:
  port: ${PORT:9100}
eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zone1
logging:
  level:
    org:
      springframework: info
    hibernate:
      SQL: debug
    com: debug
